### ISSUE TITLE
No response from proxy when RAML loaded from file://

### ISSUE THREAD

**Issue by bpytlik** [nidi3/raml-tester-proxy#22] opened 2015-07-08 02:08 UTC
Here is my raml file:

```
#%RAML 0.8

---
title: Test

protocols: [ HTTP ]

mediaType: application/json


/bar:
  description: Collection of available foo.
  get:
    description: Retrieve a list of foo.
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "type": "string",
                "required": "true"
              }
```

I have a server running on port 25001. I start the proxy using this command:

```
java -jar ./dev_deps/node_modules/raml-tester/bin/raml-tester-standalone.jar -thttp://localhost:25001 -rfile:///<path>/test_api.raml -s./ -p25099
```

If I do a curl request directly against the server, things work. Specifically, I see the request and response in my server logs and then curl prints the result:

```
$ curl -vk http://localhost:25001/bar
* About to connect() to localhost port 25001 (#0)
*   Trying ::1... Connection refused
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 25001 (#0)
> GET /bar HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.13.6.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: localhost:25001
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: application/json
< X-Response-Time: 1.084ms
< Date: Wed, 08 Jul 2015 02:03:27 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
* Closing connection #0
```

When I try to connect to the proxy however, I still see the request hitting the server and it responding (in the server log), but curl never sees a response from the server:

```
$ curl -vk http://localhost:25099/bar
* About to connect() to localhost port 25099 (#0)
*   Trying ::1... connected
* Connected to localhost (::1) port 25099 (#0)
> GET /bar HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.13.6.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: localhost:25099
> Accept: */*
> 
```

After waiting more than 2 minutes, I gave up. Is this a bug or am I doing something wrong?

**Comment by ddossot** [comment] 2015-07-08 03:22
I use version `0.8.1` extensively to validate integration and production APIs and can testify that it works great.

The version brought by the node module is pretty old (`0.0.4`) so get the latest JAR from Maven central and use it instead: http://search.maven.org/#browse|1760247101

This said version `0.0.4` was already pretty much functional so it must be something else. What does the proxy output on startup and when the test request hits it?

**Comment by bpytlik** [comment] 2015-07-08 21:34
Ok, I've updated to the version provided above and I see the same results.

Here's the proxy command and the entire output:

```
$ java -jar ./raml-tester-standalone-0.8.1.jar -thttp://localhost:25001 -rfile:///<pth>/test_api.raml -s./ -p25099
[main] INFO guru.nidi.ramlproxy.report.Reporter - Reporting in TEXT format into: .
[main] INFO guru.nidi.ramlproxy.jetty.JettyProxyServlet - Proxy started

```

**Comment by ddossot** [comment] 2015-07-08 22:04
I've found how to reproduce your issue: it seems that if the RAML file is loaded with `file:///` the proxy doesn't work. I load my RAML files over HTTP so I've never had the problem (I expose RAML files over HTTP so I can dynamically generate a value for `baseUri` as explained [here](http://stackoverflow.com/a/30678657/387927)).

I've tried to force the base URI with `-b` hoping that it could clear up the issue but to no avail so @nidi3 I think this is a legit bug.

@bpytlik Could you please append `"when RAML loaded from file://"` to this issue's title?

**Comment by nidi3** [comment] 2015-07-08 22:06
I'll have a look at it tomorrow.
Thanks @ddossot for the help!

**Comment by nidi3** [comment] 2015-07-09 09:10
Just tried it and it works on my machine :disappointed: 

To be sure: 
- When you load the RAML using http://, it works fine. 
- When you load the RAML using file://, the proxy never responds.
  Right?

Can you tell if the proxy calls the server (localhost:25001)?

**Comment by nidi3** [comment] 2015-07-09 09:15
But in #23 the proxy responds? What's the difference in the setup?

**Comment by nidi3** [comment] 2015-07-09 11:13
Ok, I think the problem is that the RAML doesn't contain a 'baseUri'.
It's a bug that I'm going to fix. 
Meanwhile can you try and add a baseUri and see if it helps?

**Comment by nidi3** [comment] 2015-07-09 15:07
fixed on trunk

**Closed as completed** 2015-07-14 19:10 UTC

**Comment by mik01aj** [comment] 2015-07-27 15:19
I'm having the same issue. I just installed the latest `raml-tester` (0.0.4) from npm and get the same output as @bpytlik.

I see that the requests are forwarded to my server, but I never get a reply from the proxy. There is also no log output on request (I don't know if it should be like this).
